global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: "default"

  routes:
    - matchers:
        - severity = "critical"
      receiver: "autoremediate"

    - matchers:
        - severity = "warning"
      receiver: "default"

receivers:
  - name: "default"
    slack_configs:
      - api_url: "https://hooks.slack.com/services/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"
        channel: "#prometheus-grafana"
        send_resolved: true
        title: "{{ .CommonAnnotations.summary }}"
        text: "{{ .CommonAnnotations.description }}"

  - name: "autoremediate"
    webhook_configs:
      - url: "http://172.27.164.211:5000/webhook"
        send_resolved: true  # Envía alertas resueltas también (opcional)