groups:
  - name: cpu_alerts
    rules:
      - alert: HighCPUUsage
        expr: avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[1m])) < 0.2
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High CPU Usage detected"
          description: "CPU usage is above 80% for the last minute."
