global:
  scrape_interval: 15s  # Intervalo en el que Prometheus recolecta métricasscrape_configs:  

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['172.27.164.211:9100']
